version: '3'

services:
  jupyterlab:
    # image: jupyter/tensorflow-notebook:latest
    build:
      context: .
      dockerfile: Dockerfile
    user: root
    environment:
      NB_UID: 1000
      NB_GID: 100
      GRANT_SUDO: "yes"
    volumes:
       - "../jupyterlab:/home/jovyan/work"
       - "../data:/home/jovyan/data"
       - "../model_data:/home/jovyan/model_data"
    privileged: true
    ports:
      - "8888:8888"
    restart: unless-stopped
    command: start.sh jupyter lab --NotebookApp.token=''